<a href="https://colab.research.google.com/github/LINGA9001/python-git-pjt1/blob/main/data_preprocessing_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
gtpip install pandas


In [ ]:
import pandas as pd
data=pd.read_csv('Data.csv')


In [ ]:
data.columns
data['Country']
data['Age'][6]
data.head(1)
data.tail(2)


Country   Age   Salary Purchased
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#step - 2 :seperate both i/p and o/p variables
#independent variables
#y=f(x)
X=data.iloc[:,0:-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#dependent variables
Y=data.iloc[:,-1].values
Y


array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
pip install sklearn


In [ ]:
#step-3: talk about  missing data
#MISSING DATA IN x
#missing data = nan
from sklearn.impute import SimpleImputer
import numpy as  np
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])#identification 
X[:,1:3]=imputer.transform(X[:,1:3])

In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
#taking care of string data
#independent variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=ct.fit_transform(X)


[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
X

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
#encode the independent variable
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [ ]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#step - 5: feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X[:,3:5]=sc.fit_transform(X[:,3:5])


In [ ]:
X

array([[0.0, 1.0, 0.0, -0.6546536707079771, 0.758874361590019, 72000.0],
       [1.0, 0.0, 0.0, 1.5275252316519463, -1.7115038793306814, 48000.0],
       [1.0, 0.0, 1.0, -0.6546536707079771, -1.2755547779917342, 54000.0],
       [1.0, 0.0, 0.0, 1.5275252316519463, -0.1130238410878753, 61000.0],
       [1.0, 0.0, 1.0, -0.6546536707079771, 0.17760889313808945,
        63777.77777777778],
       [0.0, 1.0, 0.0, -0.6546536707079771, -0.5489729424268225, 58000.0],
       [1.0, 0.0, 0.0, 1.5275252316519463, 0.0, 52000.0],
       [0.0, 1.0, 0.0, -0.6546536707079771, 1.3401398300419485, 79000.0],
       [1.0, 0.0, 1.0, -0.6546536707079771, 1.6307725642679132, 83000.0],
       [0.0, 1.0, 0.0, -0.6546536707079771, -0.2583402082008577, 67000.0]],
      dtype=object)

In [ ]:
#step - 6: splitting the data into train and test

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2) 


In [ ]:
Y_test

array([0, 1])

In [ ]:
Y_train

array([0, 1, 0, 1, 1, 0, 0, 1])

In [ ]:
X_test

array([[1.0, 0.0, 1.0, -0.6546536707079771, -1.2755547779917342, 54000.0],
       [1.0, 0.0, 0.0, 1.5275252316519463, -1.7115038793306814, 48000.0]],
      dtype=object)

In [ ]:
X_train

array([[0.0, 1.0, 0.0, -0.6546536707079771, 0.758874361590019, 72000.0],
       [0.0, 1.0, 0.0, -0.6546536707079771, -0.2583402082008577, 67000.0],
       [1.0, 0.0, 1.0, -0.6546536707079771, 1.6307725642679132, 83000.0],
       [0.0, 1.0, 0.0, -0.6546536707079771, 1.3401398300419485, 79000.0],
       [1.0, 0.0, 1.0, -0.6546536707079771, 0.17760889313808945,
        63777.77777777778],
       [1.0, 0.0, 0.0, 1.5275252316519463, 0.0, 52000.0],
       [1.0, 0.0, 0.0, 1.5275252316519463, -0.1130238410878753, 61000.0],
       [0.0, 1.0, 0.0, -0.6546536707079771, -0.5489729424268225, 58000.0]],
      dtype=object)